meta_product_name: "Daycare Diary"
meta_title: "Daycare Diary - Fast & easy way to communicate with parents"
meta_description: "Daycare Diary is ideal for daycare employees to keep track of all the kids throughout the day and to inform the parents automatically."
meta_image: url('https://res.cloudinary.com/dvrahrooa/image/upload/v1631181785/daycarediary_cover_x194kg.svg')
